AI response should be in embed
Together-Java/TJ-Bot pull request #1046
Opened 2024-03-06 23:09 UTC by ankitsmt211

* helper method to generate embed
* remove AI parser class that partitioned responses & related tests
* refactor dismiss button on generated responses
* update docs
* resolves #917 and possibly #935 (since now response embed contains title)

Here's how new AI generated responses look like: 

![gpt-response-embed](https://github.com/Together-Java/TJ-Bot/assets/61616007/cc4f7416-dacb-4ab6-8abb-1af2570ea136)

2024-03-07 16:51 UTC, SquidXTV approved these changes
Looks good to me :D
Btw you want to change the user icon to chatgpt icon?
Are we even allowed to?

2024-03-07 17:13 UTC, ankitsmt211 commented
>  Btw you want to change the user icon to chatgpt icon? Are we even allowed to?

that would be really nice if we could do that, i can't think of a way to do that. Prolly would need store random asset somewhere and get a url perhaps that we can pass for author.

2024-03-07 17:15 UTC, SquidXTV commented
> > Btw you want to change the user icon to chatgpt icon? Are we even allowed to?
> 
> that would be really nice if we could do that, i can't think of a way to do that. Prolly would need store random asset somewhere and get a url perhaps that we can pass for author.

https://en.m.wikipedia.org/wiki/File:ChatGPT_logo.svg
https://chat.openai.com/apple-touch-icon.png
https://chat.openai.com/favicon-32x32.png

2024-03-07 17:16 UTC, ankitsmt211 commented
I will give these a try, also i linked a new issue #928 since it will be resolved as well so we can touch 3 of the issues with this merge.

2024-03-12 09:04 UTC, Taz03 requested changes

2024-03-12 09:04 UTC, Taz03 commented on application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java
> +            .setAuthor(selfUser.getName(), null, selfUser.getEffectiveAvatarUrl())
maybe add gpt as author?

2024-03-12 09:05 UTC, Taz03 approved these changes

2024-03-12 09:54 UTC, merged