upgrade to java 22
Together-Java/TJ-Bot pull request #1071
Opened 2024-03-22 18:40 UTC by Taz03

2024-03-22 18:55 UTC, Taz03 commented
The workflows cannot be on Java 22, because gradle itself doesn't support Java 22 it only supports running code on Java 22.

This is from gradle release notes:-
![image](https://github.com/Together-Java/TJ-Bot/assets/73871477/72203e20-26d3-4278-a245-d7d12245017e)

2024-03-22 18:57 UTC, SquidXTV commented
> The workflows cannot be on Java 22, because gradle itself doesn't support Java 22 it only supports running code on Java 22.
> 
> This is from gradle release notes:- ![image](https://private-user-images.githubusercontent.com/73871477/316139160-72203e20-26d3-4278-a245-d7d12245017e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzQxMDMsIm5iZiI6MTcxMTEzMzgwMywicGF0aCI6Ii83Mzg3MTQ3Ny8zMTYxMzkxNjAtNzIyMDNlMjAtMjZkMy00Mjc4LWEyNDUtZDdkMTIyNDUwMTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE4NTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMmIzZDZmNGJkMTk0OTdlYzhmNjA0NGMwMjMyYmRjYWQ2MTdmMzIyYzhlZDJmMTgxNjEzZGVjYTU4MzkzOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Qr_4k9n7o2lJcMiLUW6wrRCSNExwyEhfN_UrQD2Bu0)

but compiling to java 22 works fine right? just not running the daemon with java 22, right?

2024-03-22 18:59 UTC, Taz03 commented
@SquidXTV Yes, compiling works fine. That's why the tests pass

2024-03-25 07:47 UTC, Zabuzard requested changes
Blocked at least until Adoptium offers Java 22 on the main page (i.e. after official release).

2024-03-27 19:43 UTC, SquidXTV commented
> Blocked at least until Adoptium offers Java 22 on the main page (i.e. after official release).

It does right?
https://adoptium.net/temurin/releases/?version=22

2024-04-13 14:16 UTC, SimonVerhoeven commented
It would be nice to see this one merged.

2024-04-14 13:07 UTC, Taz03 commented
**THIS PR IS OPEN FOR SOMEONE ELSE TO TAKE OVER, OR CLOSE**

2024-06-01 02:09 UTC, SquidXTV commented
gradle 8.8 released so this can be finished

2024-06-01 04:14 UTC, Taz03 commented
blocked by #1123

2024-06-06 23:46 UTC, Taz03 commented
Issue related to sonarlint failing https://community.sonarsource.com/t/java-21-unamed-pattern-error/109839

2024-06-07 09:06 UTC, SquidXTV commented
> Issue related to sonarlint failing https://community.sonarsource.com/t/java-21-unamed-pattern-error/109839

It is talking about preview features and java 21. How is this related?

2025-07-01 09:35 UTC, merged