change to getFirst() and getLast()
Together-Java/TJ-Bot pull request #1127
Opened 2024-06-04 20:05 UTC by nefelhhh

Closes #1091.

2024-06-04 20:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Together-Java/TJ-Bot?pullRequest=1127) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Together-Java/TJ-Bot?pullRequest=1127) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Together-Java/TJ-Bot?pullRequest=1127) it.</sub>

2024-06-05 04:27 UTC, SquidXTV commented
I still found a lot of `get(0)` in the codebase by using `ctrl` + `shift` + `f` to use find in files.

![getFirst](https://github.com/Together-Java/TJ-Bot/assets/88111627/4e65eabf-96e1-4161-a991-d401f2fa1bc8)

Also using this regex I could find these `getLast` opportunities, though the 4th one is false:

![getLast](https://github.com/Together-Java/TJ-Bot/assets/88111627/cf3d6255-ed10-4e88-bd08-7c2251327d37)

2024-06-05 13:20 UTC, christolis submitted a review, later dismissed

2024-06-05 13:20 UTC, SquidXTV approved these changes

2024-06-05 14:01 UTC, Taz03 requested changes
https://github.com/Together-Java/TJ-Bot/blob/7bc47d6cfdce350111e1f775d97b4f54f8d0e30d/application/src/main/java/org/togetherjava/tjbot/features/jshell/renderer/RendererUtils.java#L63

change this also

2024-06-05 14:42 UTC, Taz03 approved these changes

2024-06-05 15:04 UTC, SquidXTV approved these changes

2024-06-05 16:32 UTC, merged