Migrate temporary ban/mute
Together-Java/TJ-Bot pull request #267
Opened 2021-11-17 11:42 UTC by Zabuzard

### Overview

Dyno supports temporary bans and mutes, so should we. This adds support for such a feature. Part of #63 and #64 .

Therefore, a `duration` option is added to the existing `ban` and `mute` commands, which allows selection from a menu, such as:

![choice menu](https://i.imgur.com/meKiAhn.png)

![response](https://i.imgur.com/Rf66iFl.png)

### Details

The feature is implemented by using a new database table:
```sql
CREATE TABLE temporary_moderation_actions
(
    case_id        INTEGER   NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id        BIGINT    NOT NULL,
    guild_id       BIGINT    NOT NULL UNIQUE,
    action_type    TEXT      NOT NULL,
    action_expires TIMESTAMP NOT NULL
)
```
where each temporary action is remembered until it was revoked by a new `TemporaryModerationRoutine` class, that is executed on schedule every 5 minutes.

The routine basically selects all records from the table where `action_expires` is behind `now` and then revokes those actions by unbanning/unmuting the user.

### Notes

Error handling, such as users who got deleted in the meantime, left the guild or the even the bot leaving the guild and similar, are handled solely by `logger` messages. There is no direct feedback in any guild channel (on purpose).

![logger success](https://i.imgur.com/0OqAA45.png)

Revocation should however be picked up by the existing mod-audit-log feature:

![audit log](https://i.imgur.com/CTZ7o1m.png)

### Checklist

#### TODO

* [ ] Wait for #252 
* [ ] Add support for temp mutes
* [ ] Fix remaining issues in the code

#### Testing

Base cases:
* [ ] Perm ban
* [ ] Perm mute
* [ ] Temp ban
* [ ] Temp unmute

Bot leaves guild
* [ ] Temp ban/mute, then remove bot from guild and wait until revoke kicks in (can be mocked easily by editing the DB guildId value)

User does not exist
* [ ] Temp ban/mute, then delete user account from Discord and wait until revoke kicks in (can be mocked easily by editing the DB userId value)

User is not a member
* [ ] Temp mute user, kick user, wait until revoke kicks in

Multiple overlapping actions
* [ ] Temp ban user, then unban, then temp ban again with different time (all within less than 5 minutes (the routine schedule))

2021-11-17 11:43 UTC, Zabuzard commented
Blocked by #252

2021-11-17 19:05 UTC, RealYusufIsmail commented
Would it not be better waiting for the audit command?

2021-11-18 07:20 UTC, Zabuzard commented
> 
> 
> Would it not be better waiting for the audit command?

Why? I could ask you the same. I do not see any actual blocking dependency between the two. Only inconvenience and extra work introduced for both of them.

2021-12-03 09:05 UTC, Zabuzard commented
Blocked by #297

2021-12-10 16:20 UTC, Heatmanofurioso requested changes

2021-12-10 16:20 UTC, Heatmanofurioso commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/TemporaryModerationRoutine.java
> +        if (action != ModerationUtils.Action.BAN) {
You could call this before retrieving the guild on line 62 `jda.getGuildById(guildId);`
If the action type is unsupported, it doesn't matter of the bot is connected or not to the guild, and we won't make an "unnecessary" call to the getGuildById

2021-12-17 09:36 UTC, Zabuzard commented
Yikes, got no time to resolve the conflict before holiday anymore. Will do it afterwards 🤷

2021-12-29 17:08 UTC, Zabuzard commented
Conflict resolved (no real code change)

2021-12-29 17:13 UTC, merged

2021-12-29 17:13 UTC, Zabuzard commented
Merging since 2 weeks without actual code changes and everything looks fine.