Added ".editorconfig"
Together-Java/TJ-Bot pull request #29
Opened 2021-09-07 22:21 UTC by Zabuzard

- mostly IJ default settings, tweaked a bit.
- spaces, CRLF, 120, wrap, strict

Try it out and propose change, if any. Otherwise we will start with that as a base.

(also applied auto formatting on all files, so some changes were made - all reviewed by me)

2021-09-07 22:23 UTC, Zabuzard commented
Not sure if it works in other IDEs than Intellij. Probably not correctly, maybe in Eclipse but I did not test it.

Ideally we should provide a proper setup for Intellij, Eclipse and Netbeans, as much as possible.

Anyways, this is an Intellij setup for now.

2021-09-07 22:23 UTC, Tais993 approved these changes

2021-09-08 09:06 UTC, I-Al-Istannen requested changes

2021-09-08 09:06 UTC, I-Al-Istannen commented on .editorconfig
> +ij_java_method_call_chain_wrap = split_into_lines
I'd only chop down if necessary. I think that'd be 
```suggestion
ij_java_method_call_chain_wrap = on_every_item
```

2021-09-08 09:07 UTC, marko-radosavljevic reviewed
Do we need configs for each IDE? What about vscode or vim?

We should have auto-formatting inside the pipeline imo, so one tool that takes care of everything. Seems like a much more universal solution that will potentially save us a lot of hassle with different IDE's.

Also, it provides much more flexibility and comfort for everyone working on the project, because they can enjoy their own formatting how they like it, and on push it gets formatted for the repo.

We should also have .gitattributes with LF/crlf normalization for each file type, git gets confused on some file types, and it's an annoying thing to deal with.

2021-09-08 09:36 UTC, Zabuzard commented
There are ideas of going with a different setup that allows all (most) IDEs.
Some sort of Google Style with Spotless or similar (@I-Al-Istannen tries out some stuff).

Holding back this PR for now.

2021-09-08 13:31 UTC, d3vel0per commented on .editorconfig
> +end_of_line = crlf
Shouldnt this be just linefeed as our deployments would be on a linux box. Eg. an executable script will most likely error out with crlf 🤔
IDE's are anyways okay with both formats.

```suggestion
end_of_line = lf
```

2021-09-08 22:02 UTC, Zabuzard commented
The project went into a different direction and we now have an Eclipse Google Style configuration that can be imported into Intellij, as well as SonarLint that is setup nicely. Stuff is still going on but we definitely will not use an `.editorconfig` as suggested here.

Hence, closing this.

2021-09-08 22:02 UTC, closed without merging