Updated map of VC activities
Together-Java/TJ-Bot pull request #473
Opened 2022-07-28 00:53 UTC by Korwai

## What?
Updated names of activities to match Discord and added activities to the map.
## Why?
This should make the list of VC activities be up-to-date in terms of currently available activities.
## How?
Adjusted variable values and changed the current VC_APPLICATION_TO_ID Map to work with Map.ofEntries() rather than Map.of() since the latter takes only up to 10 elements.
## Testing?
I've tested every activity including the ones I've added and the ones that did not require a boost worked properly. I couldn't verify if the boost-required activities worked but the game icons did appear (except Sketchy Artist) when using the /vc-activity command.
## Screenshots (optional)
## Anything Else?
It seems like there are 4 games on the list that are not available to the public (Sketchy Artist, Awkword, Betrayal.io, Fishington.io) as Discord will return "This server doesn't have access to the requested activity."

2022-07-28 00:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Together-Java/TJ-Bot?pullRequest=473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Together-Java/TJ-Bot?pullRequest=473) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Together-Java/TJ-Bot?pullRequest=473) it.</sub>

2022-07-28 06:11 UTC, Zabuzard submitted a review, later dismissed

2022-07-28 06:12 UTC, Zabuzard commented
Please fix the remaining spotless issues 👍

2022-07-28 06:29 UTC, Zabuzard approved these changes

2022-07-28 06:51 UTC, Tanish-Azad approved these changes

2022-07-28 06:55 UTC, Zabuzard commented
Good job @Korwai ! Lets keep it open for another day, so that others could react as well. And then we can merge it :)

(Are you in our Discord server Together Java? If so, you would get a special badge for your contribution - couldnt find your name 😃)

2022-07-28 07:02 UTC, Korwai commented
Thanks @Zabuzard :D

I did join the Discord earlier today, my tag should be Lulee#2000 ^^

2022-07-28 09:36 UTC, Tais993 commented
In your post, you're saying fishington doesn't work. But it's added in the code.

If it doesn't work, it shouldn't be added.

2022-07-28 19:24 UTC, Korwai commented
I saw fishington.io and betrayal.io in the list beforehand so I kept them in there just for completionist-sake but I can remove them along with Sketchy Artist and Awkword if needed.

2022-07-29 06:37 UTC, Zabuzard commented
> I saw fishington.io and betrayal.io in the list beforehand so I kept them in there just for completionist-sake but I can remove them along with Sketchy Artist and Awkword if needed.

I would vote for removing anything that doesnt work. I dont want users to have bad UX.

2022-07-29 08:06 UTC, Zabuzard approved these changes

2022-07-29 09:17 UTC, Tanish-Azad requested changes
put chess game in a separate line

2022-07-29 09:22 UTC, Zabuzard commented
> put chess game in a separate line

I doubt they can. This is most likely controlled by Spotless.

2022-07-29 09:25 UTC, Tanish-Azad approved these changes

2022-07-29 09:48 UTC, Tais993 commented on application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
>       * List comes from <a href="https://github.com/DV8FromTheWorld/JDA/pull/1628">the "Implement
Update

2022-07-29 20:57 UTC, Korwai commented on application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
>       * List comes from <a href="https://github.com/DV8FromTheWorld/JDA/pull/1628">the "Implement
Updated the list source

2022-08-01 06:49 UTC, Zabuzard approved these changes

2022-08-01 12:14 UTC, Tanish-Azad approved these changes

2022-08-02 08:53 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java
>       * List comes from <a href="https://github.com/DV8FromTheWorld/JDA/pull/1628">the "Implement
@Tais993 ur fine with it now?

2022-08-05 07:36 UTC, Zabuzard commented
7 days after last activity. Merging 🙂

2022-08-05 07:36 UTC, merged