Fix sonar issues
Together-Java/TJ-Bot pull request #538
Opened 2022-08-26 23:45 UTC by mikerasch

Fixes sonar issues by adding documentation and changing access modifiers to private

2022-08-26 23:50 UTC, Zabuzard requested changes
Good stuff. But I couldnt just accept it without requesting _something_ 😄

2022-08-26 23:50 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/help/OnGuildLeaveCloseThreadListener.java
> +     * Creates a new instance
missing dot.

2022-08-26 23:50 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/help/OnGuildLeaveCloseThreadListener.java
> +     * @param database database to use
use for what?

2022-08-26 23:50 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadMetadataPurger.java
> +     * @param database the database to use
use for what?

2022-08-26 23:50 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/help/HelpThreadMetadataPurger.java
> +     * Creates a new instance
missing dot.

2022-08-26 23:50 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java
> +     * @param database the database to use
use for what?

2022-08-27 00:12 UTC, Zabuzard approved these changes

2022-08-27 00:43 UTC, marko-radosavljevic approved these changes

2022-08-27 00:56 UTC, merged