Migrate to JDA alpha 20
Together-Java/TJ-Bot pull request #587
Opened 2022-09-27 14:47 UTC by Zabuzard

## Overview

Closes #586 .

WIP.

## Checklist

Details at: https://github.com/DV8FromTheWorld/JDA/releases

* [x] 5 -> 6
* [x] 6 -> 10
* [x] 10 -> 13
* [x] 13 -> 18
* [ ] Fix tests with 18
* [ ] 18 -> 19
* [ ] 19 -> 20

2022-09-30 17:42 UTC, Taz03 requested changes

2022-09-30 17:42 UTC, Taz03 commented on application/src/main/java/org/togetherjava/tjbot/commands/BotCommandAdapter.java
> +        this.data = data.setGuildOnly(visibility == CommandVisibility.GUILD);
y u removed the non null check?

2022-10-02 17:43 UTC, Tais993 approved these changes
Me when no issues

(although gotta fix the removed requireNonNull)

![image](https://user-images.githubusercontent.com/49957334/193468221-797ee548-077d-4b4c-af3f-63897ec05b82.png)

2022-10-04 08:47 UTC, Zabuzard commented
one approve, one week old, merging

2022-10-04 08:50 UTC, merged