Automatically organize imports with spotless
Together-Java/TJ-Bot pull request #606
Opened 2022-10-04 14:19 UTC by marko-radosavljevic

This PR introduces automatic import organizing with spotless, since it's a common pain point in the workflow.
You push → sonarcloud doesn't like the unused import → you have to fix the issue and push again. 

So with this PR, we have automatic fixes for:
- newline missing at the end of files, or too many newlines at the end of files (can be extended to other files if we want, like json config etc)
- unused imports
- import order

Automatically ordering imports is not necessary, but it's a nice thing to have, since everything would be always consistent.
Import are ordered like this: external dependencies, internal org.togetherjava classes, java classes and static imports. Since that's the ordering we have been using so far. There are still small changes in a lot of files, mostly new lines between categories.

Feel free to suggest new ordering, but keep in mind it would introduce heavy merge conflicts since every PR branch has import changes. ^^

2022-10-04 14:35 UTC, Taz03 commented
> but keep in mind it would introduce heavy merge conflicts since every PR branch has import changes

they are easy to fix so no problem to me

2022-10-04 14:37 UTC, Taz03 approved these changes

2022-10-05 06:49 UTC, Zabuzard requested changes
Two things to ease migration here:
* can you adjust the `meta/formatting/google-style-eclipse.xml` file?
* can you export an IntelliJ formatter settings file and/or tell us which checkboxes to check so that it conforms?

I want my IDE to conform with the setup as much as possible, to reduce the amount of stuff that Spotless changes.

We also promote such a setup, with a small guide, in our Wiki for beginners.

2022-10-07 21:45 UTC, marko-radosavljevic commented
There shouldn't be much or any migration with this. It's not like we are changing code formatting, it's just imports, so workflow shouldn't be affected.

You write code → IDE adds imports for you, you don't even see them because they are collapsed → you commit and push and everything is organized for the repo. So ideally, this should be completely invisible to the user.

The whole idea with our fully automatic workflow was to make it beginner-friendly. So nobody has to worry about formatting and complex configuration importing in all your tooling, only to realize half of the IDEs don't even support it.

Now, I understand wanting to conform to formatting of the code, since you don't want to flip-flop completely different formatting after each commit. But who cares about imports? Since currently it's wild west anyway, everyone does imports however they want or however their tooling does it.

* * *

Now to answer your questions,

> can you adjust the meta/formatting/google-style-eclipse.xml file

No, eclipse has a separate file format for ordering imports.
Spotless can use eclipse exported import order, looks something like this
```
#Organize Import Order
#Wed Oct 05 11:50:58 CEST 2022
0=java
1=javax
2=org
3=com
```

It's a text file, and IntelliJ doesn't understand it, doubt other IDEs either.

> can you export an IntelliJ formatter settings file and/or tell us which checkboxes to check so that it conforms?

Yeah, this should give the exact same result as our spotless import order. Since I copied our current ordering and IntelliJ default as much as possible, the difference is mostly in spacing: 

![image](https://user-images.githubusercontent.com/30927961/194660718-fc3ea258-fa70-4970-8cac-b812d5e49d0f.png)

(Unable to resize the window, but the rest is same)

* * *

Ordering is not that important anyway, we can drop that commit as far as I'm concerned. Just some consistency is nice, if it comes at 0 cost.

- newline missing at the end of files, or too many newlines at the end of files (can be extended to other files if we want, like json config etc)
- unused imports

These two are actually important since they waste so much dev hours monthly, and they generate no changes at all.

2022-10-08 18:46 UTC, Zabuzard approved these changes
feel free to hit the button @marko-radosavljevic

2022-10-08 18:47 UTC, merged