Updated dm message for mod actions
Together-Java/TJ-Bot pull request #630
Opened 2022-10-15 05:31 UTC by Taz03

![image](https://user-images.githubusercontent.com/73871477/195970617-f604a9d2-c5a9-4228-9c41-2b2908838295.png)

the thumbnail image is server icon

2022-10-15 20:13 UTC, Tais993 commented
I'm sticking to my opinion that I find the guild title and the thumbnail feel really random / off.
I'd really instead use the author field like I showed in #620.

I'd love some other opinions on this

(also, next time prefix your branch with `feature` or `bug` and such, a.e `feature/moderation-message-improvement`

2022-10-15 21:28 UTC, Taz03 commented
@Tais993 turns out i can put the second value as `null` and it'll work, doing it then

also zabu said branch name doesn't really matter but yea i can do that it'll just be harder for me to type everytime

2022-10-16 18:57 UTC, marko-radosavljevic commented
How would it look like with a slightly bigger reason, for example for:

> A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend...

Which would be a medium-sized reasoning, that is very commonly used. Because currently it looks like only few words would fit nicely.

2022-10-16 19:56 UTC, Taz03 commented
@marko-radosavljevic 
![image](https://user-images.githubusercontent.com/73871477/196055326-06ed6423-1def-426e-acfc-2ce4f996dfb0.png)
ik it is looking trash

what about this one
![image](https://user-images.githubusercontent.com/73871477/196055341-116db146-f6fb-4647-aa86-4467f156212d.png)

2022-10-16 19:59 UTC, marko-radosavljevic commented
Yeah, I think the second one is nice. :relaxed:

2022-10-16 20:00 UTC, Taz03 commented
> Yeah, I think the second one is nice. relaxed

ok pushing the changes

2022-10-17 07:50 UTC, Zabuzard commented
i like the options we have with the formatting. looks much nicer.

however, the actual message is less friendly now. it is very important that those messages are super friendly and with smileys and whatever. the old messages were better.

we want that users who behaved bad will adapt and come back. so we have to be very kind to them when showing them a message that they have been temp banned or warned. they must perceive it as "its all good, dont worry. we want u in our community. just adapt please, thanks"

2022-10-17 13:35 UTC, Zabuzard requested changes
ur latest changes miss which server. the bot is designed to be able to run on multiple guilds/servers at the same time

2022-10-17 14:21 UTC, Taz03 commented
> ur latest changes miss "which server" in the messages. the bot is designed to be able to run on multiple guilds/servers at the same time

actually the server details are already given at the top as author so i thought its ok if just remove it, do u want them back?

2022-10-18 07:01 UTC, Zabuzard commented
could u update ur PR description with the up2date pictures? id like to see how everything looks before i review, cause that massively helps the review process.

2022-10-18 10:24 UTC, Zabuzard commented
> > could u update ur PR description with the up2date pictures? id like to see how everything looks before i review, cause that massively helps the review process.
> 
> it is already updated

i thought u wanted to make the messages friendlier?

2022-10-18 10:52 UTC, Tais993 commented
> i thought u wanted to make the messages friendlier?

![image](https://user-images.githubusercontent.com/49957334/196410380-2de777bc-0b21-4efc-8fe6-14a51c7c0db8.png)

This is the current message, so yes, it's a lot friendlier.

But I don't like that it says "MUTE" in the title, I'd personally prefer something like "You have been muted"

2022-10-18 11:44 UTC, Taz03 commented
> i thought u wanted to make the messages friendlier?

yea i did that already, u can read the msg in actual code i thought u wanted the updated ui

will update the messages once my frnd gets online and i can mute him again

2022-10-18 13:42 UTC, Taz03 commented
> But I don't like that it says "MUTE" in the title, I'd personally prefer something like "You have been muted"

i'd like to stay with the current format coz this way the user can know everything at a glance and won't need to read through text

like its a mute and for this duration and for this reason. and now it also explains it in the description

2022-10-18 14:11 UTC, Zabuzard commented
Im okay with a short title like `Mute`. But it needs to be user friendly, so `Mute`, not `MUTE`. otherwise u get the feeling that someone is screaming at u.

2022-10-19 06:53 UTC, Zabuzard requested changes

2022-10-19 06:53 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java
> +            .setTitle(action.substring(0, 1).toUpperCase() + action.substring(1))
The design on this `action` seems incorrect.
1. u called it `action`, but what is it exactly? its supposed to be the **title**. but u give it the `ACTION_VERB`
2. the action verb is sth like "banned", "warned" - a verb. its not a title. You want it to say "Ban" and "Mute", not "Banned".

You should adjust the callsite and definitely improve the naming on your variable here, it should be `actionTitle` and in the javadoc it should give an example, like `"ban"`.

2022-10-19 07:43 UTC, Zabuzard requested changes

2022-10-19 07:43 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/BanCommand.java
> +                .getModActionEmbed(guild, "Ban", description, reason, duration)
better. but please put it into a constant in the class, similar to ACTION_VERB. so maybe ACTION_TITLE. same with the other classes, thanks

2022-10-19 07:44 UTC, Zabuzard commented
just as a headsup, i smell annoying merge conflicts with #493 which also touches those messages

2022-10-20 13:27 UTC, closed without merging