Enhanced mod action dm message
Together-Java/TJ-Bot pull request #647
Opened 2022-10-21 11:06 UTC by Taz03

closes #620 

![image](https://user-images.githubusercontent.com/73871477/197325204-2eb1fbcf-4421-4a0a-a2b7-7cf005990bf1.png)

todo:
- [x] use embed in dm message
- [x] use better colors
- [x] remove details on how to contact mod in non punishing actions

2022-10-24 08:20 UTC, Zabuzard requested changes
please restore the original text for all messages. u made the messages less friendly and some of them also sound a bit weird now.

just dont touch them, leave it as it is. just wrap embed around and thats it 🙂

2022-12-03 19:18 UTC, Taz03 commented
if anyone want they can take over this pr

2023-01-12 08:56 UTC, Taz03 commented
![image](https://user-images.githubusercontent.com/73871477/212022156-b05e00bb-4960-4fab-9d9f-3c9ba987b81d.png)
@Zabuzard

2023-01-12 09:17 UTC, Zabuzard commented
What about:
* unmute
* unban
* kick
* quarantine
* unquarantine
* warn

Your example covers:
* ban
* mute

Also, you suggest them in `ban` to use `/modmail`, but that doesnt work. `/modmail` can only be used if you are still in the server. So its not an option for `ban` and `kick`. (which is why the old messages dont suggest it for them)

2023-01-12 11:12 UTC, Zabuzard commented
ah. for **unmute**, you are missing the smiley "👌 "

2023-01-22 13:39 UTC, Taz03 commented
Old vs New comparison

Quarantine
![image](https://user-images.githubusercontent.com/73871477/213918596-c9836473-49a1-42fa-947d-0825c61e98c7.png)
![image](https://user-images.githubusercontent.com/73871477/213918607-afcdaa73-96be-4e9a-ac48-a31895063565.png)

Unquarantine
![image](https://user-images.githubusercontent.com/73871477/213918658-51b6d867-53a6-4a3a-b957-c2edefa79e36.png)
![image](https://user-images.githubusercontent.com/73871477/213918667-685faad7-4ef7-4c53-9f62-bf29b2216b47.png)

Mute
![image](https://user-images.githubusercontent.com/73871477/213918698-c9954b87-4c7d-4428-a7ef-5b41b83b1cbd.png)
![image](https://user-images.githubusercontent.com/73871477/213918710-c70f1276-a050-4a21-a4c5-08cbf87c96d0.png)

Unmute
![image](https://user-images.githubusercontent.com/73871477/213918750-b87ca3c7-d115-48e4-acc7-a3c2b100e82f.png)
![image](https://user-images.githubusercontent.com/73871477/213918760-8ace4ce1-a9d4-4fc4-afef-6a8644b607c2.png)

Kick
![image](https://user-images.githubusercontent.com/73871477/213918785-f3c0b556-f278-4103-9240-a7446be25270.png)
![image](https://user-images.githubusercontent.com/73871477/213918792-2aa7a43f-735a-4374-8804-823fe35b2eef.png)

Ban
![image](https://user-images.githubusercontent.com/73871477/213918806-c01ac2ea-5016-4279-8e62-e30645170ef9.png)
![image](https://user-images.githubusercontent.com/73871477/213918813-1c75c4a9-3f69-4624-9ea6-b3e2499846c4.png)

2023-01-22 13:48 UTC, Taz03 commented
@Zabuzard

2023-01-23 08:15 UTC, Zabuzard commented
Thanks for the comparisons. Now please adjust the code to spit out the same messages and then Im happy.

* ban/kick: dont suggest /modmail
* kick: missing "from the server.", missing "If you think this was a mistake, ..."
* ban: missing "If you think this was a mistake, ..."
* unmute: missing 👌
* mute: missing "you can simply use /modmail **here in this chat**. Your message ...😊"
* unquarantine: missing 👌 
* quarantine: missing "you can simply use /modmail **here in this chat**. Your message ...😊"
* warn: missing "you can simply use /modmail **here in this chat**. Your message ... 😊"

2023-01-27 20:43 UTC, Taz03 commented
> kick: missing "from the server.", missing "If you think this was a mistake, ..."

server name is moved at the top

2023-01-27 20:55 UTC, Taz03 commented
@Zabuzard done

2023-01-30 07:54 UTC, Zabuzard requested changes

2023-01-30 07:54 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/BanCommand.java
> +                If you this this was a mistake, please contact a moderator or admin of this server
* "this this" -> "think this"
* missing dot at the end of the sentence

2023-01-30 07:54 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/KickCommand.java
> +                If you this this was a mistake, please contact a moderator or admin of this server
same

2023-01-30 07:54 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java
> +                    "%n%nTo get in touch with a moderator, you can use the %s command here in this chat. Your message will then forwarded and a moderator will get back to you soon 😊"
* will then [be] forwarded

2023-01-30 07:54 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java
> +            String description, String reason, boolean showModmail) {
`showModmail` sounds weird. maybe `showModmailAdvice`. and the javadoc then maybe `whether to advice on how to use the modmail command`

2023-01-30 07:54 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/commands/moderation/MuteCommand.java
> +                        """;
please test that the newline behavior is correct here, since u ended `"""` on the next line and not on the same

2023-02-06 14:05 UTC, Taz03 commented
@Zabuzard 1 week passed with no other review, merge now?

2023-02-07 08:38 UTC, merged