Top helpers not askers
Together-Java/TJ-Bot pull request #763
Opened 2023-02-03 19:43 UTC by Taz03

closes #762

2023-02-06 08:29 UTC, Zabuzard requested changes

2023-02-06 08:29 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/features/tophelper/TopHelpersMessageListener.java
> +    boolean isSentByOp(MessageReceivedEvent event) {
dont think its meaningful to expose this for now. id go for private

2023-02-06 08:30 UTC, Zabuzard commented
TopHelper unit tests crash, because you introduced new methods into the flow that havent been mocked yet. Do you want to fix this urself or should someone else take that part over?

2023-02-06 08:30 UTC, Zabuzard commented
Has to be done in the `JdaTestHelper` main class or whatever its called

2023-02-06 08:57 UTC, Taz03 commented
> TopHelper unit tests crash, because you introduced new methods into the flow that havent been mocked yet. Do you want to fix this urself or should someone else take that part over?

i haven't tried yet, i'll like to try that myself first, will update on it

2023-02-06 13:30 UTC, Taz03 commented
@Zabuzard for some reason when i use shorthand method it passes the test, is it ok?

2023-02-07 08:37 UTC, Zabuzard commented
> 

i suppose that method is mocked already - lol!

fair enough, i guess

2023-02-07 08:37 UTC, Zabuzard approved these changes

2023-02-07 14:54 UTC, SquidXTV approved these changes

2023-02-07 15:03 UTC, merged