reopening transfer feature PR
Together-Java/TJ-Bot pull request #895
Opened 2023-09-21 22:19 UTC by ankitsmt211

Adds transfer feature
* implemented suggested changes
* fixes #868

2023-09-21 22:26 UTC, ankitsmt211 commented
i believe the it's failing because of 
![image](https://github.com/Together-Java/TJ-Bot/assets/61616007/2a2730ae-7014-4168-9177-cd29499555e2)

2023-09-22 07:12 UTC, Zabuzard commented
rebase please

2023-09-22 11:40 UTC, ankitsmt211 commented
Linking screenshots from the original PR, all the steps are intact except step 7 and no more pings when linking new post in source channel, only username is mentioned(since a DM and a mention in new post is already done).
 https://github.com/Together-Java/TJ-Bot/pull/885#issuecomment-1723088379

2023-09-22 16:58 UTC, Taz03 requested changes

2023-09-22 17:14 UTC, Taz03 requested changes

2023-09-22 17:14 UTC, Taz03 commented on application/src/main/java/org/togetherjava/tjbot/features/moderation/TransferQuestionCommand.java
> +                        onFailure)))
don't log here

2023-09-23 22:10 UTC, ankitsmt211 commented
I'm thinking to refactor the process, 
Earlier
* Create post
* Mention OP
* DM OP
* link to new post with OP's name in source channel

Suggested
* Create Post
* Mention OP in post
* DM OP

Reasons: Since Op is mentioned twice during the process, they are already redirected to new post. There's no benefit to posting link to new post apart from possibily adding unwanted text source channel along with promotion of newly created post.

2023-09-24 02:22 UTC, Taz03 commented
Agree, but i'd say give the creator an ephemeral message in source channel linking the forum post

2023-09-26 12:18 UTC, ankitsmt211 commented
> Agree, but i'd say give the creator an ephemeral message in source channel linking the forum post

Seems like ephermal messages can be only sent to interactions, but OP is not the one interacting. So any ideas with that?

2023-09-26 15:27 UTC, ankitsmt211 commented
> Agree, but i'd say give the creator an ephemeral message in source channel linking the forum post

Do you mean maybe whoever is doing the transfer? Since that makes sense if they were able to make the transfer complete?

2023-09-26 16:15 UTC, marko-radosavljevic commented
> I'm thinking to refactor the process

Agree, will copy my response from previous PR:
> Not a fan of "three" back to back mentions are being triggered here for OP
> 
>     * on creation of new post
> 
>     * private DM
> 
>     * link to newly created post in source channel

I agree, let's get rid of the mention in source channel.

That way we don't annoy and confuse the newcomer with mentions all over the place. They only get mentioned where we want them to go, to a correct help thread. Additionally, we keep the source channel clean, and don't interrupt ongoing discussions.

Seems like a cleaner and more streamlined approach. :relaxed:

2023-09-26 16:20 UTC, marko-radosavljevic commented
> Seems like ephermal messages can be only sent to interactions, but OP is not the one interacting. So any ideas with that?

Yeah, as far as I know, it's not possible to do something like that.

> Do you mean maybe whoever is doing the transfer? Since that makes sense if they were able to make the transfer complete?

An ephemeral message to the person doing the transfer is probably not needed, they already know what happened and why. There isn't much to notify them about, either.

2023-09-26 17:20 UTC, ankitsmt211 commented
I was able to squeeze all of it into "one" chain, and make functional. Failed DM's are handled inside `dmUser` using `ErrorFlatMap`.
Apart from that, should i log anything else from this chain? 

  ```java  
@Override
    public void onModalSubmitted(ModalInteractionEvent event, List<String> args) {
        event.getJDA()
            .retrieveUserById(args.get(0))
          .map(user->user)
          .flatMap(fetchedUser->createForumPost(event, fetchedUser))
          .flatMap(user->dmUser(event.getChannel(), user))
          .flatMap(deleted->event.reply("transferred to"+deleted.getAsMention()).setEphemeral(true))
          .flatMap(info->deleteOriginalMessage(event.getJDA(),args.get(2),args.get(1)))
            .queue();
    }
```
>  .flatMap(deleted->event.reply("transferred to"+deleted.getAsMention()).setEphemeral(true))

Needed to reply to event, otherwise modal menu wouldn't close and showed error at the top. 

if this is good to go, i can commit and push for any further tweaks.

2023-09-27 23:26 UTC, closed without merging