add java doc for config and a typo fix
Together-Java/TJ-Bot pull request #956
Opened 2023-11-17 16:59 UTC by ankitsmt211

* adds java doc for `getSelectRolesChannelPattern()`
* teeny typo fix `selectRolesChannelPatten`-->`selectRolesChannelPattern`

2023-11-18 01:25 UTC, Taz03 submitted a review, later dismissed

2023-11-18 08:43 UTC, Zabuzard requested changes

2023-11-18 08:43 UTC, Zabuzard commented on application/src/main/java/org/togetherjava/tjbot/config/Config.java
> +     * Gets the REGEX pattern used to identify the role selection channel.
try to use javadoc to elaborate on what the code doesnt directly explain already. for example:

> ... to identify the channel in which users can select their helper roles.

2023-11-18 13:20 UTC, Taz03 approved these changes

2023-11-19 19:06 UTC, Zabuzard approved these changes

2023-11-19 19:28 UTC, merged