Disabled Features should be logged #898
Together-Java/TJ-Bot pull request #980
Opened 2023-12-09 13:22 UTC by Abhishekk24

I added a feature to log a message when a certain function is turned off. This log message will help us know which features are disabled and understand why. It's like a notification that tells us, "Hey, we turned off this specific feature, and here's why." This can be useful for keeping track of the configuration and troubleshooting any issues related to disabled features.

2023-12-09 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Together-Java/TJ-Bot?pullRequest=980) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Together-Java/TJ-Bot?pullRequest=980) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Together-Java/TJ-Bot?pullRequest=980) it.</sub>

2023-12-10 08:57 UTC, Zabuzard commented
@Abhishekk24 Note that the issue ur fixing was already assigned to another user, who also already created a solution at #899 .

So you might have done "double work" here. Ideally, before starting on an issue, you should get yourself assigned to it first - and if its already assigned to someone, coordinate quickly 🙂

2023-12-10 09:20 UTC, Abhishekk24 commented
Sure will consider this for further work . Thank you.

On Sun, 10 Dec, 2023, 14:27 Daniel Tischner, ***@***.***>
wrote:

> @Abhishekk24 <https://github.com/Abhishekk24> Note that the issue ur
> fixing was already assigned to another user, who also already created a
> solution at #899 <https://github.com/Together-Java/TJ-Bot/pull/899> .
>
> So you might have done "double work" here. Ideally, before starting on an
> issue, you should get yourself assigned to it first - and if its already
> assigned to someone, coordinate quickly 🙂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Together-Java/TJ-Bot/pull/980#issuecomment-1848900025>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5RZLCMIQ5IYRELDIE7FW3LYIV2P5AVCNFSM6AAAAABANZQ732VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBYHEYDAMBSGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-11 09:04 UTC, Zabuzard commented
Please fix the issues mentioned by the failing checks, thanks.

2023-12-11 09:15 UTC, Abhishekk24 commented
yes sure

2023-12-11 10:42 UTC, Abhishekk24 commented
If there are anymore errors please guide me.. This is all new to me

2023-12-12 04:46 UTC, Taz03 requested changes

2023-12-12 04:46 UTC, Taz03 commented on application/src/main/java/org/togetherjava/tjbot/features/Features.java
> +            Logger logger) {
y don't u just create  a  logger in this class

2023-12-12 04:46 UTC, Taz03 commented on application/src/main/java/org/togetherjava/tjbot/features/Features.java
> +        }).toList();
as u can see using peek is forbidden, so just put the log in filter method.

Also ur changing the logic before it removed the blacklisted features and kept all others, now it'll do the opposite

2024-03-16 23:19 UTC, closed without merging

2024-03-16 23:24 UTC, Taz03 commented
merged #1048